### ISSUE TITLE
Decide on a central chat platform

### ISSUE THREAD

**Issue by Xaeroxe** [ruiwg/about-us#4]
We're going to need to talk, a lot, and while issue trackers and pull requests can be good tools we should have some kind of IM as well.

Discord seems popular and I like it. I'd also consider Slack. How do our members feel about these platforms?

**Comment by mralve** [comment]
Well, I think that Discord is currently sufficient, IMO.

**Comment by Xaeroxe** [comment]
I assigned some people to make sure everyone saw this. Thoughts?

**Comment by borup3** [comment]
I prefer Slack but Discord is a better platform for this. Slack's history limitation for free use will eventually be a show stopper.

**Comment by happenslol** [comment]
I think it really depends on whether this group is just for internal communication, or external as well. Discord is great because it facilitates outside people just "stopping by", but I hate how messages get "swallowed" really quickly in discord.

As for Slack, there's always self-hostable alternatives. There's rocket.chat (which I don't like) and MatterMost (which I haven't tried but looks great), and many more - It would probably be the safest route to just go with discord in the short term though.

**Comment by Xaeroxe** [comment]
Here's our new discord: https://discordapp.com/invite/CrBeshh
